/**
 * Build-time robots.txt generator — keeps the Sitemap URL in sync with the
 * configured site origin so staging never points at prod (and vice versa).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const SITE_URL = (process.env.VITE_SITE_URL || "https://wowstack.com").replace(/\/$/, "");

// AI / answer-engine crawlers we explicitly allow (AEO).
const aiBots = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "PerplexityBot", "ClaudeBot", "Google-Extended"];

const robots = `# Wowstack — generated by scripts/generate-robots.js
User-agent: *
Allow: /
Disallow: /dashboard
Disallow: /admin
Disallow: /api/

${aiBots.map((b) => `User-agent: ${b}\nAllow: /\n`).join("\n")}
Sitemap: ${SITE_URL}/sitemap.xml
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../public/robots.txt");
writeFileSync(out, robots);
console.log(`[seo] robots.txt written → ${out}`);
